// Game status enums
export enum GamePhase {
  WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
  REINFORCEMENT_5 = 'REINFORCEMENT_5',
  REINFORCEMENT_3 = 'REINFORCEMENT_3',

  PAUSED = 'PAUSED',
  FINISHED = 'FINISHED',

}
